version: '3.8'

services:
  admin_service:
    build: ./backend/admin_service  # Вказує папку, в якій знаходиться Dockerfile
    ports:
      - "3000:3000"  # Порт, на якому буде доступний сервіс
    depends_on:
      - pg           # Залежить від сервісу бази даних
      - redis        # Залежить від Redis

  collector_service:
    build: ./backend/collector_service  # Вказує папку, в якій знаходиться Dockerfile
    depends_on:
      - pg          # Залежить від сервісу бази даних
      - redis       # Залежить від Redis

  frontend_service:
    build: ./frontend_service   # Вказує папку, в якій знаходиться Dockerfile
    ports:
      - "3001:3001"  # Порт для фронтенду
    depends_on:
      - admin_service

  pg:
    image: postgres:latest  # Використовує останню версію PostgreSQL
    restart: always
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/postgresql/data  # Постійне зберігання даних бази даних

  redis:
    image: redis:latest  # Використовує останню версію Redis
    restart: always

  prometheus:
    image: prom/prometheus:latest  # Використовує останню версію Prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Конфігураційний файл для Prometheus

  grafana:
    image: grafana/grafana:latest  # Використовує останню версію Grafana
    ports:
      - "3001:3000"  # Доступ до Grafana на порту 3001
    depends_on:
      - prometheus

volumes:
  db_data:  # Оголошення тому для зберігання даних бази даних