apiVersion: 1

datasources:
  - name: postgres-datasource
    uid: pgds
    orgId: 1
    type: postgres
    access: proxy
    url: pg:5432
    database: currency_analyzer
    user: dev
    basicAuth: false
    secureJsonData:
      password: "dev"
    jsonData:
      sslmode: "disable"
      tlsAuth: false
      tlsAuthWithCACert: false
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: false
    isDefault: false
  - name: prometheus-datasource
    uid: prometheus
    orgId: 1
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
    isDefault: true
 